/* Simillar with libc,
 * but with additional saves of usd_(lo,hi) and psp_(lo,hi) */
std::arch::global_asm! {
    ".ignore ld_st_style",
    ".ignore strict_delay",
    ".text",
    ".global crash_context_getcontext",
    ".hidden crash_context_getcontext",
    ".type crash_context_getcontext, #function",
    ".align 8",
"crash_context_getcontext:",
"{{",
    "setwd wsz = 0x9, nfx = 0x1, dbl = 0x0",
    "setbn rsz = 0x4, rbs = 0x4, rcur = 0x1",
"}}",
"{{",
    "rrd,0 %psp.hi, %r2",
    "addd,1 0x0, 0x4, %b[0]",
    "addd,2 0x0, %r0, %b[1]",
    "sdisp  %ctpr1, 6",
"}}",
"{{",
    "rrd,0 %cr0.hi, %r3",
    "addd,1 0x0, 0x8, %b[2]",
    "std,2 %r0, _f16s 0x68, %r2",
"}}",
"{{",
    "rrd,0 %cr1.lo, %r2",
    "std,2 %r0, _f16s 0x30, %r3",
"}}",
"{{",
    "rrd,0 %cr1.hi, %r3",
    "addd,1,sm     0x0, %r0, %r2",
    "std,2 %r0, _f16s 0x38, %r2",
"}}",
"{{",
    "rrd,0 %psp.lo, %r4",
    "std,2 %r0, _f16s 0x40, %r3",
"}}",
"{{",
    "rrd,0 %usd.hi, %r3",
    "std,2 %r0, _f16s 0x60, %r4",
"}}",
"{{",
    "rrd,0 %usd.lo, %r4",
    "std,2 %r0, _f16s 0x58, %r3",
"}}",
"{{",
    "std,2 %r0, _f16s 0x50, %r4",
    "call   %ctpr1, wbs = 0x5",
"}}",
"{{",
    "return        %ctpr3",
    "addd,0        0x0, %db[0], %r3",
    "cmpbedb,1     %db[0], _f16s 0xf000, %pred0",
    "subd,2,sm     0x0, %db[0], %r4",
"}}",
"{{",
    "disp  %ctpr1, __errno_location",
"}}",
"{{",
    "sxt,3 0x2, %r3, %r0 ? %pred0",
    "call  %ctpr1, wbs = 0x5 ? ~%pred0",
"}}",
"{{",
    "ct    %ctpr3 ? %pred0",
    "subd,3        0x0, 0x1, %r0 ? ~%pred0",
    "stw,5 %b[0], 0x0, %r4 ? ~%pred0",
"}}",
"{{",
    "nop 1",
    "return        %ctpr3",
"}}",
"{{",
    "ct    %ctpr3 ? ~%pred0",
"}}",
    ".size crash_context_getcontext, . - crash_context_getcontext",
}
